server.port: 6060

kontur:
  kinfra:
    mongodb:
      enabled: true
      database: snowone
      login: root
      password: root
      replica-set: 172.19.0.2,172.19.0.3,172.19.0.4
  rabbit:
    enabled: true
    host: 172.17.0.2
    username: user
    password: password